name: Release

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Install tools
      run: |
        go install github.com/tc-hib/go-winres@latest
        go install github.com/go-gl/glow@latest

    - name: Generate
      run: make generate

    - name: Test
      run: make test

    - name: Build
      env:
        CGO_ENABLED: 1
        GOOS: windows
        GOARCH: amd64
      run: make release EXECNAME=neoray-windows

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: windows
        path: |
          bin/neoray-windows.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Install tools
      run: go install github.com/go-gl/glow@latest

    - name: Generate
      run: make generate

    - name: Test
      run: make test

    - name: Build
      env:
        CGO_ENABLED: 1
        GOOS: darwin
        GOARCH: amd64
      run: make release EXECNAME=neoray-macos

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: macos
        path: |
          bin/neoray-macos

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Set up required libs
      run: |
        sudo apt update && sudo apt upgrade
        sudo apt install libx11-dev libgtk-3-dev libgl1-mesa-dev xorg-dev

    - name: Install tools
      run: go install github.com/go-gl/glow@latest

    - name: Generate
      run: make generate

    - name: Test
      run: make test

    - name: Build
      env:
        CGO_ENABLED: 1
        GOOS: linux
        GOARCH: amd64
      run: make release EXECNAME=neoray-linux

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: linux
        path: |
          bin/neoray-linux
